# Generated by Django 2.2.11 on 2020-03-23 07:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Row',
                'verbose_name_plural': 'Rows',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='WikiEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contributor_name', models.CharField(max_length=100)),
                ('contributor_email', models.EmailField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Row')),
            ],
            options={
                'verbose_name': 'WikiEntry',
                'verbose_name_plural': 'WikiEntries',
                'ordering': ['row', 'column', 'position'],
            },
        ),
    ]
