# Generated by Django 2.2.11 on 2020-03-24 08:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Register',
                'ordering': ['position'],
            },
        ),
    ]
