# Generated by Django 2.2.11 on 2020-03-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['register', 'position'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['register', 'position'], 'verbose_name': 'Row', 'verbose_name_plural': 'Rows'},
        ),
        migrations.AddField(
            model_name='column',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Register'),
        ),
        migrations.AddField(
            model_name='row',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Register'),
        ),
    ]
