# Generated by Django 2.2.11 on 2020-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20200324_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikientry',
            options={'ordering': ['row', 'column', 'timestamp'], 'verbose_name': 'WikiEntry', 'verbose_name_plural': 'WikiEntries'},
        ),
        migrations.RemoveField(
            model_name='wikientry',
            name='position',
        ),
        migrations.AddField(
            model_name='wikientry',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
