# Generated by Django 2.2.11 on 2020-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20200324_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
