# Generated by Django 2.2.11 on 2020-03-25 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20200325_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Register'),
        ),
        migrations.AlterField(
            model_name='row',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Register'),
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
